apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
  labels:
    app: kibana
spec:
  # 복제본 수
  replicas: 1
  # 라벨 셀렉터
  selector:
    matchLabels:
      app: kibana
  # 포드 템플릿
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:7.13.4
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch.default.svc.cluster.local:9200"
            - name: ELASTICSEARCH_SCHEME
              value: "http"
            - name: FLUENT_UID
              value: "0"
          ports:
            - containerPort: 5601

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
  name: kibana-svc
  namespace: default
spec:
  ports:
    - port: 5601
      protocol: TCP
      targetPort: 5601
      nodePort: 30433
      name: http
  selector:
    app: kibana
  type: LoadBalancer
